FROM node:16.17.0
WORKDIR /home/some_project_name
RUN apt-get update
RUN npm install -g npm@8.15.0
RUN npm install -g prettier
RUN npm i -g @nestjs/cli
RUN npm install -g typescript
ENTRYPOINT ["tail", "-f", "/dev/null"]