apiVersion: apps/v1
kind: Deployment
metadata:
  name: triage-tool-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: dshusdock/ple-triage-server:prod1
          # Added resources (resoource limits) to quiet down the linter
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          #############################################################
          ports:
            - containerPort: 3001

              